/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ngmsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ngmsg.pb-c.h"
void   ngmsg__init
                     (NGmsg         *message)
{
  static NGmsg init_value = NGMSG__INIT;
  *message = init_value;
}
size_t ngmsg__get_packed_size
                     (const NGmsg *message)
{
  assert(message->base.descriptor == &ngmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngmsg__pack
                     (const NGmsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngmsg__pack_to_buffer
                     (const NGmsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NGmsg *
       ngmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NGmsg *)
     protobuf_c_message_unpack (&ngmsg__descriptor,
                                allocator, len, data);
}
void   ngmsg__free_unpacked
                     (NGmsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ngmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ngmsg__field_descriptors[4] =
{
  {
    "c",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NGmsg, has_c),
    offsetof(NGmsg, c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rtm",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(NGmsg, has_rtm),
    offsetof(NGmsg, rtm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NGmsg, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NGmsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngmsg__field_indices_by_name[] = {
  0,   /* field[0] = c */
  3,   /* field[3] = d */
  2,   /* field[2] = ip */
  1,   /* field[1] = rtm */
};
static const ProtobufCIntRange ngmsg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ngmsg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NGmsg",
  "NGmsg",
  "NGmsg",
  "",
  sizeof(NGmsg),
  4,
  ngmsg__field_descriptors,
  ngmsg__field_indices_by_name,
  1,  ngmsg__number_ranges,
  (ProtobufCMessageInit) ngmsg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
