/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ngmsg.proto */

#ifndef PROTOBUF_C_ngmsg_2eproto__INCLUDED
#define PROTOBUF_C_ngmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _NGmsg NGmsg;


/* --- enums --- */


/* --- messages --- */

/*
 ** message main body *
 */
struct  _NGmsg
{
  ProtobufCMessage base;
  /*
   ** status *
   */
  protobuf_c_boolean has_c;
  int32_t c;
  /*
   ** timestamp *
   */
  protobuf_c_boolean has_rtm;
  int64_t rtm;
  /*
   ** ip *
   */
  char *ip;
  /*
   ** log content *
   */
  char *d;
};
#define NGMSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngmsg__descriptor) \
    , 0,0, 0,0, NULL, NULL }


/* NGmsg methods */
void   ngmsg__init
                     (NGmsg         *message);
size_t ngmsg__get_packed_size
                     (const NGmsg   *message);
size_t ngmsg__pack
                     (const NGmsg   *message,
                      uint8_t             *out);
size_t ngmsg__pack_to_buffer
                     (const NGmsg   *message,
                      ProtobufCBuffer     *buffer);
NGmsg *
       ngmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngmsg__free_unpacked
                     (NGmsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NGmsg_Closure)
                 (const NGmsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ngmsg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ngmsg_2eproto__INCLUDED */
